/*
 * LUMA DAILY — Shared Product Data
 * Single source of truth for all product/bundle data used across pages
 */

export const products = [
  {
    id: 1,
    slug: "energy",
    name: "Energy",
    fullName: "Luma Energy",
    tagline: "Natural vitality, sustained",
    headline: "Power your day without the crash.",
    image: "/manus-storage/luma_energy_bottle_18c415cd.png",
    description: "Ginseng, B12 & Green Tea Extract to power your day without the crash.",
    longDescription:
      "Luma Energy is formulated for those who want clean, sustained vitality without the jitters or crash of caffeine-heavy products. Ginseng Root supports physical endurance and mental clarity, while Vitamin B12 fuels cellular energy production. Green Tea Extract provides a gentle, natural lift, and CoQ10 supports mitochondrial function for lasting stamina.",
    price: 27.99,
    originalPrice: 37.99,
    subscribePrice: 22.39,
    color: "#F5C842",
    bgColor: "#FEF9E7",
    textColor: "#7A5C00",
    gummyColor: "#F5C842",
    ingredients: [
      { name: "Ginseng Root", dose: "200mg", benefit: "Supports physical endurance and mental clarity" },
      { name: "Vitamin B12", dose: "1000mcg", benefit: "Fuels cellular energy production" },
      { name: "Green Tea Extract", dose: "150mg", benefit: "Gentle, natural lift without jitters" },
      { name: "CoQ10", dose: "50mg", benefit: "Supports mitochondrial function" },
    ],
    badge: "Best Seller",
    flavor: "Blood Orange Mango",
    howToUse: "Take 2 gummies in the morning with or without food. Best taken before 2pm.",
    certifications: ["Vegan", "Gluten-Free", "Non-GMO", "Third-Party Tested"],
    reviews: 847,
    rating: 4.9,
  },
  {
    id: 2,
    slug: "calm",
    name: "Calm",
    fullName: "Luma Calm",
    tagline: "Stress less, live more",
    headline: "Quiet the noise. Find your center.",
    image: "/manus-storage/luma_calm_bottle_14cc2d8f.png",
    description: "Ashwagandha & L-Theanine to quiet the noise and find your center.",
    longDescription:
      "Luma Calm is designed for the modern mind — constantly stimulated, rarely at rest. KSM-66 Ashwagandha, the most clinically studied form, reduces cortisol and supports a calm, focused state. L-Theanine promotes alpha brain waves for relaxed alertness, while Lemon Balm and Magnesium work together to ease tension and support a steady mood throughout the day.",
    price: 27.99,
    originalPrice: 37.99,
    subscribePrice: 22.39,
    color: "#7A9E7E",
    bgColor: "#EEF5EF",
    textColor: "#2D5A32",
    gummyColor: "#7DC47E",
    ingredients: [
      { name: "Ashwagandha KSM-66", dose: "300mg", benefit: "Reduces cortisol, supports calm focus" },
      { name: "L-Theanine", dose: "200mg", benefit: "Promotes relaxed alertness" },
      { name: "Lemon Balm", dose: "150mg", benefit: "Eases tension and mild anxiety" },
      { name: "Magnesium Glycinate", dose: "100mg", benefit: "Supports steady mood and relaxation" },
    ],
    badge: "Fan Favorite",
    flavor: "Raspberry Hibiscus",
    howToUse: "Take 2 gummies as needed for stress relief, or daily for cumulative benefit. Can be taken any time of day.",
    certifications: ["Vegan", "Gluten-Free", "Non-GMO", "Third-Party Tested"],
    reviews: 1203,
    rating: 4.9,
  },
  {
    id: 3,
    slug: "sleep",
    name: "Sleep",
    fullName: "Luma Sleep",
    tagline: "Rest deeply, wake ready",
    headline: "Restorative sleep that actually refreshes.",
    image: "/manus-storage/luma_sleep_bottle_a6f93589.png",
    description: "Melatonin & Chamomile for restorative sleep that actually refreshes.",
    longDescription:
      "Luma Sleep is a gentle, non-habit-forming sleep formula built around a precise 3mg Melatonin dose — enough to signal your body it's time to rest without next-day grogginess. Chamomile Extract and Passionflower calm the nervous system and ease the transition to sleep, while GABA supports deeper, more restorative sleep cycles.",
    price: 24.99,
    originalPrice: 34.99,
    subscribePrice: 19.99,
    color: "#9B8EC4",
    bgColor: "#F3F0FA",
    textColor: "#3D2B7A",
    gummyColor: "#B8A8E0",
    ingredients: [
      { name: "Melatonin", dose: "3mg", benefit: "Signals the body it's time to rest" },
      { name: "Chamomile Extract", dose: "200mg", benefit: "Calms the nervous system" },
      { name: "Passionflower", dose: "150mg", benefit: "Eases the transition to sleep" },
      { name: "GABA", dose: "100mg", benefit: "Supports deeper sleep cycles" },
    ],
    badge: null,
    flavor: "Blueberry Lavender",
    howToUse: "Take 2 gummies 30 minutes before bedtime. Not recommended for daytime use.",
    certifications: ["Vegan", "Gluten-Free", "Non-GMO", "Third-Party Tested"],
    reviews: 692,
    rating: 4.8,
  },
  {
    id: 4,
    slug: "focus",
    name: "Focus",
    fullName: "Luma Focus",
    tagline: "Clarity on demand",
    headline: "Sharp thinking. Sustained concentration.",
    image: "/manus-storage/luma_focus_bottle_4364c9ab.png",
    description: "Lion's Mane & Bacopa for sharp thinking and sustained concentration.",
    longDescription:
      "Luma Focus supports the brain's natural capacity for deep work. Lion's Mane Mushroom promotes Nerve Growth Factor (NGF) production for long-term cognitive health. Bacopa Monnieri, used in Ayurvedic medicine for centuries, improves memory retention and processing speed. Ginkgo Biloba enhances cerebral blood flow, and Vitamin B6 supports neurotransmitter synthesis.",
    price: 29.99,
    originalPrice: 39.99,
    subscribePrice: 23.99,
    color: "#6AACCC",
    bgColor: "#EBF5FA",
    textColor: "#1A4E6A",
    gummyColor: "#6AACCC",
    ingredients: [
      { name: "Lion's Mane Mushroom", dose: "500mg", benefit: "Promotes NGF for cognitive health" },
      { name: "Bacopa Monnieri", dose: "300mg", benefit: "Improves memory and processing speed" },
      { name: "Ginkgo Biloba", dose: "120mg", benefit: "Enhances cerebral blood flow" },
      { name: "Vitamin B6", dose: "10mg", benefit: "Supports neurotransmitter synthesis" },
    ],
    badge: "New",
    flavor: "Spearmint Green Tea",
    howToUse: "Take 2 gummies in the morning. Best results seen with consistent daily use over 4–6 weeks.",
    certifications: ["Vegan", "Gluten-Free", "Non-GMO", "Third-Party Tested"],
    reviews: 421,
    rating: 4.8,
  },
  {
    id: 5,
    slug: "glow",
    name: "Glow",
    fullName: "Luma Glow",
    tagline: "Beauty from within",
    headline: "Radiant skin, strong nails, lustrous hair.",
    image: "/manus-storage/luma_glow_bottle_c1ab2dea.png",
    description: "Collagen & Vitamin C for radiant skin, strong nails, and lustrous hair.",
    longDescription:
      "Luma Glow is a comprehensive beauty-from-within formula. Marine Collagen Peptides support skin elasticity and hydration, while Vitamin C is essential for collagen synthesis. Biotin strengthens nails and hair, and Hyaluronic Acid helps maintain skin moisture from the inside out. The result: a visible glow that starts at the cellular level.",
    price: 29.99,
    originalPrice: 39.99,
    subscribePrice: 23.99,
    color: "#E8917A",
    bgColor: "#FDF0EC",
    textColor: "#7A2A14",
    gummyColor: "#E8917A",
    ingredients: [
      { name: "Marine Collagen Peptides", dose: "2500mg", benefit: "Supports skin elasticity and hydration" },
      { name: "Vitamin C", dose: "500mg", benefit: "Essential for collagen synthesis" },
      { name: "Biotin", dose: "5000mcg", benefit: "Strengthens nails and hair" },
      { name: "Hyaluronic Acid", dose: "100mg", benefit: "Maintains skin moisture from within" },
    ],
    badge: null,
    flavor: "Strawberry Peach",
    howToUse: "Take 2 gummies daily, preferably with a meal. Best results seen after 4–6 weeks of consistent use.",
    certifications: ["Vegan", "Gluten-Free", "Non-GMO", "Third-Party Tested"],
    reviews: 934,
    rating: 4.9,
  },
  {
    id: 6,
    slug: "gut",
    name: "Gut",
    fullName: "Luma Gut",
    tagline: "Digestive harmony, daily",
    headline: "A balanced gut microbiome, every day.",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663633783733/NP8W4PN5hdBACVumhQ3AtE/luma_gut_bottle-XRZKo6DKmqn38DjNUJpCzw.webp",
    description: "Probiotics, Prebiotics & Digestive Enzymes for a balanced gut microbiome and smooth digestion.",
    longDescription:
      "Luma Gut is a complete digestive wellness formula. 10 Billion CFU of clinically studied probiotic strains rebalance the gut microbiome, while Inulin Prebiotic feeds the beneficial bacteria. A full-spectrum Digestive Enzyme blend supports the breakdown of proteins, fats, and carbohydrates, and Ginger Root soothes the digestive tract and reduces bloating.",
    price: 24.99,
    originalPrice: 34.99,
    subscribePrice: 19.99,
    color: "#7AAE6E",
    bgColor: "#EFF6EC",
    textColor: "#2A5C1A",
    gummyColor: "#A8D49A",
    ingredients: [
      { name: "Probiotics (10B CFU)", dose: "10B CFU", benefit: "Rebalances the gut microbiome" },
      { name: "Inulin Prebiotic", dose: "500mg", benefit: "Feeds beneficial gut bacteria" },
      { name: "Digestive Enzymes", dose: "200mg", benefit: "Supports breakdown of all macronutrients" },
      { name: "Ginger Root", dose: "150mg", benefit: "Soothes the digestive tract" },
    ],
    badge: "New",
    flavor: "Citrus Mint",
    howToUse: "Take 2 gummies with your largest meal of the day. Consistent daily use recommended for best results.",
    certifications: ["Vegan", "Gluten-Free", "Non-GMO", "Third-Party Tested"],
    reviews: 318,
    rating: 4.7,
  },
];

export const bundles = [
  {
    id: 1,
    slug: "energy-calm",
    name: "Energy + Calm",
    subtitle: "Energy + Calm",
    description: "The perfect pair for a productive, balanced day. Fuel your morning and stay centered through it all.",
    price: 49.99,
    originalPrice: 55.98,
    image: "/manus-storage/energy_calm_bundle_7ba4902a.png",
    products: ["Energy", "Calm"],
  },
  {
    id: 2,
    slug: "sleep-glow",
    name: "Sleep + Glow",
    subtitle: "Sleep + Glow",
    description: "Rest deeply and wake radiant. Your overnight beauty and recovery ritual in one.",
    price: 49.99,
    originalPrice: 54.98,
    image: "/manus-storage/sleep_glow_bundle_e2009a50.png",
    products: ["Sleep", "Glow"],
  },
  {
    id: 3,
    slug: "glow-up",
    name: "Glow Up Bundle",
    subtitle: "Glow + Sleep + Calm",
    description: "Radiant skin, restful nights, and a calm mind. The ultimate self-care trio.",
    price: 69.99,
    originalPrice: 82.97,
    image: "/manus-storage/glow_up_bundle_d7d92b3b.png",
    products: ["Glow", "Sleep", "Calm"],
  },
  {
    id: 4,
    slug: "performance",
    name: "Performance Bundle",
    subtitle: "Energy + Focus + Calm",
    description: "Sharpen your edge. Designed for peak mental and physical performance every day.",
    price: 74.99,
    originalPrice: 85.97,
    image: "/manus-storage/performance_bundle_3fa231f4.png",
    products: ["Energy", "Focus", "Calm"],
  },
  {
    id: 5,
    slug: "focus-gut",
    name: "Focus + Gut Bundle",
    subtitle: "Focus + Gut Health",
    description: "The gut-brain connection, optimized. Think clearly and feel great from the inside out.",
    price: 49.99,
    originalPrice: 57.98,
    image: "/manus-storage/focus_gut_bundle_3ab9febe.png",
    products: ["Focus", "Gut"],
  },
  {
    id: 6,
    slug: "focus-wellness",
    name: "Focus Wellness Bundle",
    subtitle: "Focus + Calm + Sleep",
    description: "Complete cognitive wellness — sharpen focus, reduce stress, and recover overnight.",
    price: 69.99,
    originalPrice: 82.97,
    image: "/manus-storage/focus_wellness_bundle_2f0d84d6.png",
    products: ["Focus", "Calm", "Sleep"],
  },
  {
    id: 7,
    slug: "beauty-wellness",
    name: "Beauty Wellness Bundle",
    subtitle: "Glow + Calm + Energy",
    description: "Look good, feel good. A beauty-forward ritual that nourishes inside and out.",
    price: 74.99,
    originalPrice: 85.97,
    image: "/manus-storage/beauty_wellness_bundle_8f28c04d.png",
    products: ["Glow", "Calm", "Energy"],
  },
  {
    id: 8,
    slug: "mind-body-gut",
    name: "Mind Body Gut Bundle",
    subtitle: "Focus + Energy + Gut",
    description: "Holistic wellness from the inside out. Mind, body, and gut in perfect harmony.",
    price: 74.99,
    originalPrice: 85.97,
    image: "/manus-storage/mind_body_gut_bundle_6671797c.png",
    products: ["Focus", "Energy", "Gut"],
  },
  {
    id: 9,
    slug: "daily-ritual",
    name: "Daily Ritual Bundle",
    subtitle: "All Six Formulas",
    description: "Your complete daily ritual. All six formulas working in harmony, morning to night.",
    price: 139.99,
    originalPrice: 167.94,
    image: "/manus-storage/daily_ritual_bundle_48b2976a.png",
    products: ["Energy", "Calm", "Sleep", "Focus", "Glow", "Gut"],
    featured: true,
  },
  {
    id: 10,
    slug: "essential-six",
    name: "Essential Six Bundle",
    subtitle: "All Six Formulas",
    description: "The complete Luma system. Every need, every moment, every day — fully covered.",
    price: 139.99,
    originalPrice: 167.94,
    image: "/manus-storage/essential_five_bundle_f256b0c0.png",
    products: ["Energy", "Calm", "Sleep", "Focus", "Glow", "Gut"],
  },
];

export type Product = typeof products[0];
export type Bundle = typeof bundles[0];
